# Site settings
title: Webcamp Ljubljana 2015
email: 
description: "Webcamp Ljubljana 2015"
baseurl: ""
url: ""


# Build settings
markdown: kramdown
permalink: pretty


sass:
    sass_dir: assets/stylesheet/_sass
    style: compressed
